version: '3'
services:
    app:
        restart: always
        extra_hosts:
            host.docker.internal: host-gateway
        networks:
            - simple-sound-bot
        depends_on:
            - lavalink
    lavalink:
        image: 'fredboat/lavalink:master-v3'
        restart: always
        volumes:
            - 'ssblavalink:/data'
            - './docker/lavalink.yml:/opt/Lavalink/application.yml'
        networks:
            - simple-sound-bot
        expose:
            - 2333 
networks:
    simple-sound-bot:
        driver: bridge
volumes:
    ssblavalink:
        driver: local